In [1]:
import os
import pandas as pd

In [2]:
data_folder = "data"

files = [f for f in os.listdir(data_folder) if f.endswith(".csv")]
print("Files found:", files)

df_list = []

for file in files:
    temp = pd.read_csv(os.path.join(data_folder, file))
    temp["Season"] = file.replace(".csv", "")
    df_list.append(temp)

df = pd.concat(df_list, ignore_index=True)

print("Shape:", df.shape)
df.head()

Files found: ['SP1 (7).csv', 'SP1 (6).csv', 'SP1 (1).csv', 'SP1.csv', 'SP1 (3).csv', 'SP1 (2).csv', 'SP1 (9).csv', 'SP1 (5).csv', 'SP1 (4).csv', 'SP1 (8).csv']
Shape: (3700, 180)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP1,18/08/17,Leganes,Alaves,1,0,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,18/08/17,Valencia,Las Palmas,1,0,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,19/08/17,Celta,Sociedad,2,3,A,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,19/08/17,Girona,Ath Madrid,2,2,D,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,19/08/17,Sevilla,Espanol,1,1,D,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
missing = df.isnull().sum()
print(missing[missing > 0].sort_values(ascending=False))

LBCA    3482
CLCH    3482
LBCD    3482
LBCH    3482
CLCA    3482
        ...
PSD       95
PSH       95
PSCH      93
PSCD      93
PSCA      93
Length: 154, dtype: int64

In [4]:
threshold = len(df) * 0.5
df_clean = df.dropna(axis=1, thresh=threshold)

print("Original shape:", df.shape)
print("After dropping sparse columns:", df_clean.shape)

Original shape: (3700, 180)
After dropping sparse columns: (3700, 103)

In [5]:
columns_to_keep = [
    'Date', 'HomeTeam', 'AwayTeam',
    'FTHG', 'FTAG', 'FTR',
    'HTHG', 'HTAG', 'HTR',
    'HS', 'AS', 'HST', 'AST',
    'HF', 'AF', 'HC', 'AC',
    'HY', 'AY', 'HR', 'AR',
    'Season'
]

df_clean = df_clean[columns_to_keep]
print(df_clean.shape)
df_clean.head()

(3700, 22)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
0,18/08/17,Leganes,Alaves,1,0,H,1,0,H,16,...,3,14,18,4,2,0,1,0,0,SP1 (7)
1,18/08/17,Valencia,Las Palmas,1,0,H,1,0,H,22,...,4,25,13,5,2,3,3,0,1,SP1 (7)
2,19/08/17,Celta,Sociedad,2,3,A,1,1,D,16,...,6,12,11,5,4,3,1,0,0,SP1 (7)
3,19/08/17,Girona,Ath Madrid,2,2,D,2,0,H,13,...,3,15,15,6,0,2,4,0,1,SP1 (7)
4,19/08/17,Sevilla,Espanol,1,1,D,1,1,D,9,...,6,14,12,7,3,2,4,1,0,SP1 (7)

In [6]:
raw_dates = df_clean['Date'].astype(str).str.strip()

date_long = pd.to_datetime(raw_dates, format='%d/%m/%Y', errors='coerce')
date_short = pd.to_datetime(raw_dates, format='%d/%m/%y', errors='coerce')

df_clean['Date'] = date_long.fillna(date_short)

print(df_clean[['Date']].head(10))
print("Missing dates:", df_clean['Date'].isnull().sum())

        Date
0 2017-08-18
1 2017-08-18
2 2017-08-19
3 2017-08-19
4 2017-08-19
5 2017-08-20
6 2017-08-20
7 2017-08-20
8 2017-08-21
9 2017-08-21
Missing dates: 0

In [ ]:
df_clean = df_clean.dropna(subset=['Date'])
print("After dropping missing dates:", df_clean.shape) # drop rows where there is no Date

After dropping missing dates: (3700, 22)

In [ ]:
df_clean = df_clean.sort_values('Date').reset_index(drop=True)
df_clean.head() # Sorting from oldest to newest (checking only first 5)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
0,2015-08-21,Malaga,Sevilla,0,0,D,0,0,D,25,...,2,19,11,7,2,3,3,0,1,SP1 (9)
1,2015-08-22,La Coruna,Sociedad,0,0,D,0,0,D,15,...,2,16,10,5,4,3,2,0,0,SP1 (9)
2,2015-08-22,Vallecano,Valencia,0,0,D,0,0,D,8,...,4,19,11,3,3,3,1,0,0,SP1 (9)
3,2015-08-22,Ath Madrid,Las Palmas,1,0,H,1,0,H,14,...,1,11,16,4,4,2,0,0,0,SP1 (9)
4,2015-08-22,Espanol,Getafe,1,0,H,1,0,H,4,...,3,19,14,5,6,2,3,0,1,SP1 (9)

In [ ]:
print(df_clean[['Date']].head(5))
print(df_clean[['Date']].tail(5)) #check if in order

        Date
0 2015-08-21
1 2015-08-22
2 2015-08-22
3 2015-08-22
4 2015-08-22
           Date
3695 2026-03-15
3696 2026-03-15
3697 2026-03-15
3698 2026-03-15
3699 2026-03-16

In [ ]:
print(df_clean.isnull().sum()) #check to see if data is cleaned

Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
Season      0
dtype: int64

In [15]:
df_clean.head(50)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
0,2015-08-21,Malaga,Sevilla,0,0,D,0,0,D,25,...,2,19,11,7,2,3,3,0,1,SP1 (9)
1,2015-08-22,La Coruna,Sociedad,0,0,D,0,0,D,15,...,2,16,10,5,4,3,2,0,0,SP1 (9)
2,2015-08-22,Vallecano,Valencia,0,0,D,0,0,D,8,...,4,19,11,3,3,3,1,0,0,SP1 (9)
3,2015-08-22,Ath Madrid,Las Palmas,1,0,H,1,0,H,14,...,1,11,16,4,4,2,0,0,0,SP1 (9)
4,2015-08-22,Espanol,Getafe,1,0,H,1,0,H,4,...,3,19,14,5,6,2,3,0,1,SP1 (9)
5,2015-08-23,Sp Gijon,Real Madrid,0,0,D,0,0,D,6,...,8,20,4,2,5,4,0,0,0,SP1 (9)
6,2015-08-23,Ath Bilbao,Barcelona,0,1,A,0,0,D,8,...,4,16,11,2,4,3,3,0,0,SP1 (9)
7,2015-08-23,Betis,Villarreal,1,1,D,0,1,A,22,...,4,11,26,7,5,3,1,0,1,SP1 (9)
8,2015-08-23,Levante,Celta,1,2,A,0,1,A,11,...,6,12,17,4,6,1,3,1,0,SP1 (9)
9,2015-08-24,Granada,Eibar,1,3,A,0,2,A,12,...,4,5,23,6,5,1,6,1,0,SP1 (9)
10,2015-08-28,Villarreal,Espanol,3,1,H,0,1,A,14,...,2,10,20,2,3,1,6,0,0,SP1 (9)
11,2015-08-29,Barcelona,Malaga,1,0,H,0,0,D,22,...,1,4,21,15,2,0,3,0,0,SP1 (9)
12,2015-08-29,Celta,Vallecano,3,0,H,1,0,H,11,...,0,7,11,5,4,2,2,0,1,SP1 (9)
13,2015-08-29,Real Madrid,Betis,5,0,H,2,0,H,21,...,1,12,14,11,4,3,3,0,0,SP1 (9)
14,2015-08-29,Sociedad,Sp Gijon,0,0,D,0,0,D,12,...,2,10,15,6,4,4,5,0,0,SP1 (9)
15,2015-08-30,Valencia,La Coruna,1,1,D,1,1,D,12,...,3,13,15,5,7,2,1,1,0,SP1 (9)
16,2015-08-30,Eibar,Ath Bilbao,2,0,H,1,0,H,9,...,1,14,13,11,4,2,2,0,0,SP1 (9)
17,2015-08-30,Las Palmas,Levante,0,0,D,0,0,D,16,...,2,14,21,3,0,2,4,0,0,SP1 (9)
18,2015-08-30,Getafe,Granada,1,2,A,0,2,A,16,...,4,16,15,6,6,5,3,0,0,SP1 (9)
19,2015-08-30,Sevilla,Ath Madrid,0,3,A,0,1,A,25,...,7,17,13,11,1,3,4,0,0,SP1 (9)
20,2015-09-11,Levante,Sevilla,1,1,D,0,1,A,14,...,3,12,8,5,4,3,3,0,0,SP1 (9)
21,2015-09-12,Ath Madrid,Barcelona,1,2,A,0,0,D,11,...,5,17,5,1,10,3,1,0,0,SP1 (9)
22,2015-09-12,Betis,Sociedad,1,0,H,1,0,H,9,...,3,12,9,2,4,4,3,1,0,SP1 (9)
23,2015-09-12,Sp Gijon,Valencia,0,1,A,0,0,D,16,...,3,16,11,5,6,3,3,0,0,SP1 (9)
24,2015-09-12,Espanol,Real Madrid,0,6,A,0,4,A,14,...,8,19,10,5,6,2,2,0,0,SP1 (9)
25,2015-09-13,Ath Bilbao,Getafe,3,1,H,2,0,H,14,...,3,12,15,12,5,1,4,0,0,SP1 (9)
26,2015-09-13,Celta,Las Palmas,3,3,D,2,1,H,26,...,5,19,14,7,2,0,3,0,1,SP1 (9)
27,2015-09-13,Granada,Villarreal,1,3,A,0,0,D,13,...,5,16,21,8,6,2,4,0,0,SP1 (9)
28,2015-09-13,Malaga,Eibar,0,0,D,0,0,D,10,...,0,11,13,7,3,2,4,0,0,SP1 (9)
29,2015-09-14,Vallecano,La Coruna,1,3,A,1,2,A,8,...,8,12,10,5,4,2,2,1,0,SP1 (9)
30,2015-09-18,Getafe,Malaga,1,0,H,1,0,H,10,...,3,18,11,4,7,5,2,0,0,SP1 (9)
31,2015-09-19,Valencia,Betis,0,0,D,0,0,D,22,...,1,17,15,7,1,4,2,0,1,SP1 (9)
32,2015-09-19,Eibar,Ath Madrid,0,2,A,0,0,D,9,...,6,13,7,1,4,2,1,0,0,SP1 (9)
33,2015-09-19,Sociedad,Espanol,2,3,A,1,1,D,10,...,6,15,16,7,6,2,3,1,0,SP1 (9)
34,2015-09-19,Real Madrid,Granada,1,0,H,0,0,D,20,...,3,9,15,10,1,1,3,0,0,SP1 (9)
35,2015-09-20,Las Palmas,Vallecano,0,1,A,0,1,A,8,...,6,13,19,3,5,3,5,0,0,SP1 (9)
36,2015-09-20,Sevilla,Celta,1,2,A,0,2,A,13,...,5,16,16,5,5,3,5,0,1,SP1 (9)
37,2015-09-20,Villarreal,Ath Bilbao,3,1,H,1,0,H,14,...,2,17,6,9,4,4,4,0,0,SP1 (9)
38,2015-09-20,Barcelona,Levante,4,1,H,0,0,D,21,...,4,8,16,4,4,0,1,0,0,SP1 (9)
39,2015-09-20,La Coruna,Sp Gijon,2,3,A,2,3,A,19,...,4,11,16,8,3,3,3,0,0,SP1 (9)
40,2015-09-22,Ath Madrid,Getafe,2,0,H,1,0,H,12,...,2,14,10,6,1,3,2,0,0,SP1 (9)
41,2015-09-22,Espanol,Valencia,1,0,H,1,0,H,17,...,4,22,14,7,6,5,7,0,0,SP1 (9)
42,2015-09-22,Granada,Sociedad,0,3,A,0,2,A,11,...,5,20,18,4,3,5,4,0,0,SP1 (9)
43,2015-09-23,Vallecano,Sp Gijon,2,1,H,1,0,H,18,...,2,14,17,4,4,2,1,0,1,SP1 (9)
44,2015-09-23,Malaga,Villarreal,0,1,A,0,0,D,15,...,3,18,14,8,5,2,3,0,0,SP1 (9)
45,2015-09-23,Las Palmas,Sevilla,2,0,H,1,0,H,12,...,3,9,13,5,5,3,4,0,0,SP1 (9)
46,2015-09-23,Celta,Barcelona,4,1,H,2,0,H,18,...,7,19,4,5,10,2,2,0,0,SP1 (9)
47,2015-09-23,Levante,Eibar,2,2,D,0,1,A,12,...,4,13,23,4,7,2,5,0,0,SP1 (9)
48,2015-09-23,Ath Bilbao,Real Madrid,1,2,A,0,1,A,11,...,6,17,10,6,8,4,3,0,0,SP1 (9)
49,2015-09-24,Betis,La Coruna,1,2,A,0,0,D,9,...,3,11,22,3,4,3,5,0,0,SP1 (9)